#!/usr/bin/tcsh

if ( $# == 0 ) then
    echo You must supply an object.
else if ( -e ~/_/i/i/$1 ) then
    mv ~/_/i/i/$1 . && echo Done.
    if ( -e ./button && $1 == weight ) then
        echo "A passageway opens."
        ln -s . d
        ln -s . e
        ln -s . ne
        ln -s . se
        ln -s . sw
        ln -s . w
        mv .nw nw
        mv u .u
    endif
else
    echo "You don't have that."
endif